[phases.setup]
providers = ["python"]

[variables]
PYTHON_VERSION = "3.11"

[phases.install]
cmds = [
  "which python || echo 'Python not found'",
  "python --version",
  "which pip || echo 'pip not found'", 
  "python -m pip --version",
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt"
]

[phases.start]
cmd = "python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
