[phases.setup]
providers = ["python"]

[phases.install]
cmds = ["cd backend && pip install -r requirements-deploy.txt"]

[phases.start]
cmd = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"

[variables]
PYTHONPATH = "backend"
