services:
  - type: web
    name: studentconnect-backend
    runtime: python3
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements-deploy.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=$PORT
    plan: free
    env: python
    pythonVersion: 3.11.9
    region: oregon
    healthCheckPath: /
