services:
  - type: web
    name: studentconnect-backend
    runtime: python3
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=$PORT
    plan: free
    env: python
    pythonVersion: 3.11.0
    region: oregon
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
